# Generated by Django 5.1.15 on 2026-09-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('tecnologia', 'Tecnologia'), ('gestao', 'Gestão'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('outra', 'Outra')], default='outra', max_length=20)),
                ('enrollment_start', models.DateField()),
                ('enrollment_end', models.DateField()),
                ('course_start', models.DateField()),
                ('course_end', models.DateField()),
            ],
            options={
                'ordering': ['-enrollment_start'],
            },
        ),
    ]
