# Generated by Django 5.1.15 on 2026-09-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaqArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('acesso', 'Acesso'), ('matricula', 'Matrícula'), ('conteudo', 'Conteúdo'), ('avaliacao', 'Avaliação'), ('certificado', 'Certificado'), ('tecnico', 'Técnico')], max_length=20)),
                ('cycle_phase', models.CharField(choices=[('matricula', 'Matrícula'), ('andamento', 'Andamento'), ('encerramento', 'Encerramento')], max_length=20)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('not_helpful_count', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'question'],
            },
        ),
    ]
